import React from 'react';
import ReactDOM from 'react-dom';
import './App.css';
import App from './App';
import * as serviceWorker from './serviceWorker';
import {createStore} from 'redux';
import myReducer from './reducers/index';
import {Provider} from 'react-redux';
var store = createStore(myReducer);
ReactDOM.render(<Provider store={store}><App/></Provider>, document.getElementById('root'));
serviceWorker.unregister();